// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Country *string `json:"country,omitempty"`
	Books   []*Book `json:"books"`
}

type Book struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	PublishedYear *int      `json:"publishedYear,omitempty"`
	Authors       []*Author `json:"authors"`
}

type BooksBorrow struct {
	ID         string `json:"id"`
	User       *User  `json:"user"`
	Book       *Book  `json:"book"`
	BorrowedAt string `json:"borrowedAt"`
}

type BorrowStat struct {
	Book        *Book `json:"book"`
	BorrowCount int   `json:"borrowCount"`
}

type Query struct {
}

type User struct {
	ID            string  `json:"id"`
	Username      string  `json:"username"`
	Email         string  `json:"email"`
	BorrowedBooks []*Book `json:"borrowedBooks"`
}
